def show_help():
    print("\nMongoNotes CLI Help")
    print("-------------------")
    print("Commands:")
    print("  get [collection] [filters]    - Retrieve data")
    print("    Example: get notes")
    print("    Example: get users id:5")
    print("    Example: get notes status:active")
    print()
    print("  add [collection]              - Add new entry")
    print("    Example: add note")
    print("    Example: add user")
    print()
    print("  edit [collection] [id]        - Edit an existing entry")
    print("    Example: edit note 5")
    print("    Example: edit user 3")
    print()
    print("  delete [collection] [id]      - Delete an entry")
    print("    Example: delete note 7")
    print("    Example: delete user 2")
    print()
    print("  help                          - Show this help message")
    print("  exit                          - Exit the application")
    print("-------------------")